version: "3.9"
services:
  beanbag-backend:
    image: beanbag-backend
    build:
      context: ./
      dockerfile: Dockerfile.dev
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./
        target: /app/
    depends_on:
      - db
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432
    env_file:
      - ./app.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
networks:
  frontend:
    name: frontend
  backend:
    name: backend
