// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: create_question.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    quiz_id,
    description,
    timer_option,
    timer,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING ques_id, quiz_id, description, timer_option, timer, created_at, updated_at
`

type CreateQuestionParams struct {
	QuizID      sql.NullInt32
	Description string
	TimerOption bool
	Timer       int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion,
		arg.QuizID,
		arg.Description,
		arg.TimerOption,
		arg.Timer,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Question
	err := row.Scan(
		&i.QuesID,
		&i.QuizID,
		&i.Description,
		&i.TimerOption,
		&i.Timer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
