// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_question.sql

package db

import (
	"context"
)

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions
WHERE ques_id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, quesID int32) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, quesID)
	return err
}
