// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_quiz.sql

package db

import (
	"context"
)

const deleteQuiz = `-- name: DeleteQuiz :exec
DELETE FROM quizzes
WHERE quiz_id = $1
`

func (q *Queries) DeleteQuiz(ctx context.Context, quizID int32) error {
	_, err := q.db.ExecContext(ctx, deleteQuiz, quizID)
	return err
}
