// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: delete_answer.sql

package db

import (
	"context"
)

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM answers
WHERE ans_id = $1
`

func (q *Queries) DeleteAnswer(ctx context.Context, ansID int32) error {
	_, err := q.db.ExecContext(ctx, deleteAnswer, ansID)
	return err
}
