// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_question.sql

package db

import (
	"context"
)

const getQuestion = `-- name: GetQuestion :one
SELECT ques_id, quiz_id, description, timer_option, timer, created_at, updated_at FROM questions
WHERE ques_id = $1 LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, quesID int32) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, quesID)
	var i Question
	err := row.Scan(
		&i.QuesID,
		&i.QuizID,
		&i.Description,
		&i.TimerOption,
		&i.Timer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
