// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_quiz.sql

package db

import (
	"context"
)

const getQuiz = `-- name: GetQuiz :one
SELECT quiz_id, creator_id, quiz_title, description, is_priv, timer, created_at, updated_at FROM quizzes
WHERE quiz_id = $1 LIMIT 1
`

func (q *Queries) GetQuiz(ctx context.Context, quizID int32) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, quizID)
	var i Quiz
	err := row.Scan(
		&i.QuizID,
		&i.CreatorID,
		&i.QuizTitle,
		&i.Description,
		&i.IsPriv,
		&i.Timer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
