// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_answer.sql

package db

import (
	"context"
)

const getAnswer = `-- name: GetAnswer :one
SELECT ans_id, ques_id, description, is_correct, created_at, updated_at FROM answers
WHERE ans_id = $1 LIMIT 1
`

func (q *Queries) GetAnswer(ctx context.Context, ansID int32) (Answer, error) {
	row := q.db.QueryRowContext(ctx, getAnswer, ansID)
	var i Answer
	err := row.Scan(
		&i.AnsID,
		&i.QuesID,
		&i.Description,
		&i.IsCorrect,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
