// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_question.sql

package db

import (
	"context"
	"database/sql"
)

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE questions
SET
    quiz_id = COALESCE($2, quiz_id),
    description = COALESCE($3, description),
    timer_option = COALESCE($4, timer_option),
    timer = COALESCE($5, timer),
    updated_at = NOW()
WHERE ques_id = $1
RETURNING ques_id, quiz_id, description, timer_option, timer, created_at, updated_at
`

type UpdateQuestionParams struct {
	QuesID      int32
	QuizID      sql.NullInt32
	Description sql.NullString
	TimerOption sql.NullBool
	Timer       sql.NullInt32
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, updateQuestion,
		arg.QuesID,
		arg.QuizID,
		arg.Description,
		arg.TimerOption,
		arg.Timer,
	)
	var i Question
	err := row.Scan(
		&i.QuesID,
		&i.QuizID,
		&i.Description,
		&i.TimerOption,
		&i.Timer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
