// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: update_quiz.sql

package db

import (
	"context"
	"database/sql"
)

const updateQuiz = `-- name: UpdateQuiz :one
UPDATE quizzes
SET
    creator_id = COALESCE($2, creator_id),
    quiz_title = COALESCE($3, quiz_title),
    description = COALESCE($4, description),
    is_priv = COALESCE($5, is_priv),
    timer = COALESCE($6, timer),
    updated_at = NOW()
WHERE quiz_id = $1
RETURNING quiz_id, creator_id, quiz_title, description, is_priv, timer, created_at, updated_at
`

type UpdateQuizParams struct {
	QuizID      int32
	CreatorID   sql.NullInt32
	QuizTitle   sql.NullString
	Description sql.NullString
	IsPriv      sql.NullBool
	Timer       sql.NullInt32
}

func (q *Queries) UpdateQuiz(ctx context.Context, arg UpdateQuizParams) (Quiz, error) {
	row := q.db.QueryRowContext(ctx, updateQuiz,
		arg.QuizID,
		arg.CreatorID,
		arg.QuizTitle,
		arg.Description,
		arg.IsPriv,
		arg.Timer,
	)
	var i Quiz
	err := row.Scan(
		&i.QuizID,
		&i.CreatorID,
		&i.QuizTitle,
		&i.Description,
		&i.IsPriv,
		&i.Timer,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
