---
name: 01 Main Joblist

permissions:
  contents: read # clone the repo to lint
  statuses: write #read/write to repo custom statuses
  packages: write # needed to push docker image to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

jobs:
# FIRST JOB #######################################################################   
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    permissions:
      packages: write # needed to push docker image to ghcr.io

    outputs:
      image_name_tag: ${{ steps.push-image.outputs.image_name_tag }} # Output the tag for other jobs

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        # Pass the builder name to the build-push action later

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for GHCR

      - name: Build and push beanbag-backend DEV image
        id: push-image # Give this step an ID to reference its output
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.dev
          target: dev # *** SPECIFY THE 'dev' STAGE ***
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          # Define the tag using github.run_id for uniqueness
          tags: ghcr.io/${{ github.repository }}/beanbag-backend:dev-${{ github.run_id }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Output the full image name and tag generated
          outputs: type=image,name=image_name_tag
    
# NEXT JOB #######################################################################
  test-unit:
    name: Unit tests in Docker
    needs: [build-test-image] # Depends on the build job
    runs-on: ubuntu-latest

    env:
      # Define ALL variables needed by docker-compose-ci.yml
      # Database Credentials
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432

      # App Config
      PORT: 8080
      CLIENT_ORIGIN: http://localhost:3000
      AUTH0_DOMAIN: "test.auth0.com"
      AUTH0_AUDIENCE: "test-audience"
      AUTH0_CLIENT_ID: "test-client-id"
      AUTH0_CLIENT_SECRET: "test-client-secret"
      AUTH0_CALLBACK_URL: "http://localhost:3000/callback"

      BACKEND_IMAGE: ${{ needs.build-test-image.outputs.image_name_tag }}

    permissions:
      packages: read

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests using docker compose up
        run: |
          # Ensure the BACKEND_IMAGE env var is available for compose substitution
          docker compose -f docker-compose-ci.yml up --abort-on-container-exit --exit-code-from beanbag-backend