---
name: 01 Main Joblist

permissions:
  contents: read # clone the repo to lint
  statuses: write #read/write to repo custom statuses
  packages: write # needed to push docker image to ghcr.io

on:
  push:
    branches:
      - main
  pull_request:

jobs:
# FIRST JOB #######################################################################   
  build-test-image:
    name: Build Image for Testing
    runs-on: ubuntu-latest

    permissions:
      packages: write # needed to push docker image to ghcr.io

    steps:

      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push all services
        run: |
          # Export the image tag to be used by docker-compose
          export GITHUB_TAG=${{ github.run_id }}
          
          # Build and push each service using docker compose
          docker compose -f docker-compose-dev.yml build \
            --build-arg GITHUB_TAG=$GITHUB_TAG
          
          # Tag and push each service to GHCR
          docker compose -f docker-compose-dev.yml push
    
 # NEXT JOB #######################################################################   
  test-unit:
    name: Unit tests in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest

    permissions:
      packages: read
      
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run tests
        run: |
          export GITHUB_TAG=${{ github.run_id }}
          # Run tests using the same command as local Makefile
          docker compose -f docker-compose-dev.yml -f docker-compose-test.yml run --build beanbag-backend

